import './globals.css'

export const metadata = {
  title: 'Next.js Rest Api',
  description: 'Generated by Rezk Audi',
}

export default function RootLayout({ children }) {
 return (
    <html lang="en">
      <body>{children}</body>
    </html>
  )
}
